### ISSUE TITLE
User should be able to manually trigger fetching processes

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#128]
At Moderation page user should see:
 * dates of last executions of fetching processes (will be implemented in #127 )
 * two buttons (one to fetch data about new blogs and the, 2nd one to fetch new blog posts) allowing to manually trigger fetching logic

**Comment by adamdec** [comment]
I cna work on it after #95 will be verified, approved & merged :)

**Comment by adamdec** [comment]
Let me look at during a weekend.

**Comment by tdziurko** [comment]
Moving it nack to "available" :)

**Comment by goostleek** [comment]
@tdziurko you wrote:
> two buttons allowing to manually trigger fetching logic

Why two instead of one?

**Comment by tdziurko** [comment]
One to fetch data about new blogs, 2nd to fetch new blog posts.

**Comment by tgelo** [comment]
I can do this, assign to me

**Comment by tdziurko** [comment]
Done by @tgelo 👍
