### ISSUE TITLE
Allow to add/edit/remove records in MailingAddress table

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#189]
This requires #188 to be implemented. Once we have a listing of mailing addresses, we should allow to add/edit/remove records.

**Comment by kaczors** [comment]
I would like to try implement this feature.

- can I use JSR-303 validation module?
- are there any ux guidelines? ( For example new entry form should be visible all the time or should appear after "New" button is pressed? )

**Comment by tdziurko** [comment]
OK, so
* JSR-303 is ok, there is even a Wicket module to use it (check https://ci.apache.org/projects/wicket/guide/7.x/guide/single.html#forms2_4)
* UX guidelines: it's up to you, ajax is fancy but requires more effort. If I could choose I would choose option that shows a form after some button is clicked and then hides it once its work is finished.
