### ISSUE TITLE
Post newsletter on Facebook page

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#190]
When we create a new newsletter, we should also post its content to Facebook page.

**Comment by mchmielarz** [comment]
Could assign it to me, please? ;)

**Comment by mchmielarz** [comment]
And what kind of content do you mean? A short summary or just an information about the issue would suffice?

**Comment by tdziurko** [comment]
MVP: Short message and link.
Next steps:
 - think about adding or generating a image that could make these entries more attractive.
