### ISSUE TITLE
Setting connection properties on every redirection

### ISSUE THREAD

**Issue by airborn** [jvm-bloggers/jvm-bloggers#191]
[`ProtocolSwitchingAwareConnectionRedirectHandler`](https://github.com/tdziurko/jvm-bloggers/blob/85f77d4/src/main/java/pl/tomaszdziurko/jvm_bloggers/http/ProtocolSwitchingAwareConnectionRedirectHandler.java) sets timeouts only on first connection not on the redirected ones.

This is tricky to test because currently [`ProtocolSwitchingAwareConnectionRedirectHandlerSpec`](https://github.com/tdziurko/jvm-bloggers/blob/15fbb0/src/test/groovy/pl/tomaszdziurko/jvm_bloggers/http/ProtocolSwitchingAwareConnectionRedirectHandlerSpec.groovy) is asserting on `UnknownHostException` thrown by [`Url::openConnection()`](https://github.com/tdziurko/jvm-bloggers/blob/85f77d4/src/main/java/pl/tomaszdziurko/jvm_bloggers/http/ProtocolSwitchingAwareConnectionRedirectHandler.java#L121).

One way to test this may be by introducing some kind of `HttpURLConnectionFactory` but maybe someone will propose a better solution.

**Comment by tdziurko** [comment]
@airborn can we close this one?

**Comment by airborn** [comment]
@tdziurko I guess that the bug is still there. I've prepared  part of the fix in #192 but it was not completed and I finally closed the PR due to no feedback.
