### ISSUE TITLE
Duplicated utm_source parameters in 'Nowo dodane blogi i kanały video' section urls

### ISSUE THREAD

**Issue by goostleek** [jvm-bloggers/jvm-bloggers#233]
See the urls in _Nowo dodane blogi i kanały video_ section. Although the link redirects properly it has multiplied `utm_source` parameters repeated instead of a single one.

> Nowo dodane blogi i kanały video: 
> - [Maciej Aniserowicz](http://devtalk.pl/?utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_campaign=jvm-bloggers#46&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346)
> - [Paweł Zajączkowski](https://howtotrainyourjee.com/?utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_campaign=jvm-bloggers#46&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346)
> - [Polish JUG](https://vimeo.com/polishjug/videos?utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_campaign=jvm-bloggers#46&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346)
> - [GeeCON](https://vimeo.com/geecon/videos?utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_campaign=jvm-bloggers#46&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346)
> - [Confitura](http://www.youtube.com/channel/UCkVjQGf_e0JmlonPMS4VNXQ?utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_source=jvm-bloggers.com&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_medium=newsletter&utm_campaign=jvm-bloggers#46&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346&utm_campaign=jvm-bloggers%2346)

**Comment by nikom1337** [comment]
utm_campaign and utm_medium are also duplicated

**Comment by matek2305** [comment]
I think that it can be closed as when we redirect all links through app duplicates are no longer present.

**Comment by tdziurko** [comment]
True, closing as no longer relevant.
