### ISSUE TITLE
Option to subcsribe to email

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#248]
`As a User I want to fill form and have my e-mail added to subscribers list`
- form in the footer (html/css are ready)
- confirmation e-mail is required to activate subscription

**Comment by matek2305** [comment]
I think I can work on this, should confirmation be done via link with some sort of uid send when when user subscribe?

**Comment by tdziurko** [comment]
Yes, when user submits his e-mail we send confirmation e-mail with link and once it is clicked it is confirmed and next time we send an e-mail with newsletter.

We have an entity mailing_address, probably we need two new fields there: `activation_uid` and `activated` or something similar.

I will send you footer html/css via e-mail.

**Comment by matek2305** [comment]
Hi ,sorry for this taking so long bu I had pretty busy couple of weeks and didn't have time for coding after work hours. I hope that in next week I will have some free time to work on it. If you need this quickly then feel free to take this.

**Comment by ajurasz** [comment]
@matek2305 if you didn't start working on this I could take this task over?
@tdziurko it is an old issue so need to check if this is still something that we want to have?

**Comment by tdziurko** [comment]
There was only one person who send me a private request to add his email to the newsletter. I thought there will be more of them, but apparently I was wrong :) 

So I would leave it in backlog, but with a lower priority.
