### ISSUE TITLE
Feature request: RSS feed in JSON format

### ISSUE THREAD

**Issue by pwittchen** [jvm-bloggers/jvm-bloggers#251]
I think, it would be nice if it will be possible to get RSS feed in JSON format. Exemplary link can look like this: http://jvm-bloggers.com/pl/rss?format=json. Default data format could be XML as it is now.

For example, Flickr has both XML and JSON format for feed:
- http://api.flickr.com/services/feeds/photos_public.gne?id=36998705@N00&lang=en-us&format=json
- http://api.flickr.com/services/feeds/photos_public.gne?id=36998705@N00&lang=en-us&format=xml

Regards,
Piotr

**Comment by tdziurko** [comment]
Do you want to work on it? Or it is more a "feature request" ? :)

**Comment by pwittchen** [comment]
It's a feature request, but I can work on it. I just need to dive into codebase :).

**Comment by tdziurko** [comment]
You can start at `AggregatedRssFeedProducer` :)

**Comment by tmszdmsk** [comment]
I wonder, what for? In case of flickr it's JSONP not "json json", probably to allow some cross-domain ajax calls from browser.

**Comment by kraluk** [comment]
Em, is anyone finally working on that issue? :)

**Comment by tdziurko** [comment]
I assume it's free as nothing happend with it for almost 2 months :)

**Comment by kraluk** [comment]
Therefore, I'd like to try to work on this enhancement :)

**Comment by kraluk** [comment]
To be specific (my previous message could be a little bit confusing, sorry) - I'm working on it :)
