### ISSUE TITLE
Project Java formatter for Eclipse Neon has wrong indendation

### ISSUE THREAD

**Issue by RG9** [jvm-bloggers/jvm-bloggers#256]
Hello,
I can't pass checkstyle check, because formatter "eclipse-cs jvm-bloggers" is setting wrong ident for Java code :( Please look to following example for class "NewsletterIssuePage", which local changes comparing to original code from repository has only two space ident:
![screenshot from 2016-09-20 22 37 09](https://cloud.githubusercontent.com/assets/4287365/18688252/c6b9b732-7f83-11e6-91ff-9e99648de1bf.png)

Environment:
```
Eclipse Java EE IDE for Web Developers.

Version: Neon Release (4.6.0)
Build id: 20160613-1800
```

**Comment by tdziurko** [comment]
Have you tried with formatter `eclipse-java-google-style.epf` file in `config/formatters` directory?

**Comment by RG9** [comment]
Yep, I've imported these settings once again. Unfortunately both formatters have "Indentation size" set to "2". Screenshot:
![screenshot from 2016-09-20 22 55 38](https://cloud.githubusercontent.com/assets/4287365/18688620/79c9e47c-7f85-11e6-8143-bd488bd58914.png)

**Comment by RG9** [comment]
Ok, problem solved. After reimport "eclipse-cs jvm-bloggers" has "Indentation size"  = "4", which is correct.
