### ISSUE TITLE
allegro.tech posts not included in the company's posts section

### ISSUE THREAD

**Issue by wendigo** [jvm-bloggers/jvm-bloggers#263]
Hi,

Is this a bug or is it a feature?

Most of allegro.tech's blog posts are ommited in JVM Bloggers. Why is it so?

**Comment by tdziurko** [comment]
Not a feature definitely. Will look at it, but could you provide some examples?

**Comment by wendigo** [comment]
http://allegro.tech/feed.xml

Last posts not included in issues:

- opel — asynchronous expression language - Fri, 30 Sep 2016 14:39:12 +0000
- Performance and Availability pitfalls in the Microservices Architecture — CQK Top 10 - Fri, 23 Sep 2016 00:00:00 +0000
- Thread pools — CQK Top 10 - Wed, 21 Sep 2016 00:00:00 +0000
- JVM Garbage Collection — CQK Top 10 - Wed, 21 Sep 2016 00:00:00 +0000
- Caching — CQK Top 10 - Wed, 21 Sep 2016 00:00:00 +0000

Missing from last 3 issues as I can tell:
https://groups.google.com/forum/#!topic/warszawa-jug/7q9aOWdn2wA - none included
https://groups.google.com/forum/#!topic/warszawa-jug/BzqyZTrOPmc - none included
https://groups.google.com/forum/#!topic/warszawa-jug/krWVZMXNOPY - none included

Last working example is:
https://groups.google.com/forum/#!topic/warszawa-jug/BsBniG5o1B0 including

Are code reviews worth your time? Fri, 16 Sep 2016 00:00:00 +0000

**Comment by tdziurko** [comment]
Ok, so this is caused by the fact that application is using datePublished value from RSS to get posts from last 7 days and for example post about opel has this date in rss xml:
`<pubDate>Fri, 30 Sep 2016 00:00:00 +0000</pubDate>` so it is longer than 7 days ago (last issue took posts since 1/10/2016 00:00).

I will think about possible fix to this as other people also raised similar problem.

**Comment by wendigo** [comment]
Opel post was not included also in the previous issue.

**Comment by tdziurko** [comment]
Because there are two things:
1. Value in pubDate in RSS (probably generated when someone starts writing a post) 
2. Date when it actually appears in rss, probably 1-2 days ago when someone clicked "Publish" on your blog.

**Comment by kaczors** [comment]
Working on this

**Comment by kaczors** [comment]
https://github.com/jvm-bloggers/jvm-bloggers/commit/fa5511f13ba0ae4f2adfac35eba08767472add1c

**Comment by tdziurko** [comment]
Fixed
