### ISSUE TITLE
Greeting section in mail template should contain automatically filled link to the current issue.

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#269]
Currently mailing greeting needs to be manually prepared to contian link to current issue:

```
Witajcie

Wersja webowa aktualnego wydania: http://jvm-bloggers.com/issue/57
```

This should be changed so application replaces defined placeholder with correct link, eg.

```
Witajcie

Wersja webowa aktualnego wydania: $currentIssueLink
```

**Comment by kaczors** [comment]
Working on that.

**Comment by kaczors** [comment]
https://github.com/jvm-bloggers/jvm-bloggers/commit/9277395dc7971d26614a44233275d79cb174c137

**Comment by tdziurko** [comment]
Done by @kaczors
