### ISSUE TITLE
In admin panel show list of blog posts from given blog

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#270]
In admin panel there is a list of blogs with option to deactivate "dead" ones, but it would be useful to be able to see list of blog posts for a given blog.

**Comment by kaczors** [comment]
In Progress

**Comment by kaczors** [comment]
@tdziurko 
1. Where the list should be visible? Should I add additional column with button "Post list", "Posts preview" or sth like that?
2. How the list should be presented? Should it be for example pop-up with titles of the blog's posts?
3. Should all the posts be presented (with appropriate pagination) or just for example last X ones?

**Comment by tdziurko** [comment]
Answers:
_1. Where the list should be visible? Should I add additional column with button "Post list", "Posts preview" or sth like that?_
Additional column with link/button sounds good.

_2. How the list should be presented? Should it be for example pop-up with titles of the blog's posts?_
I thought about separate page with data-table under some readable url /admin/blog/{id}/posts or something similar.

_3. Should all the posts be presented (with appropriate pagination) or just for example last X ones?_
All of them.

**Comment by kaczors** [comment]
Done, merged.
