### ISSUE TITLE
Get rid of jsonId in JSON files

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#287]
Field `jsonId` exists only to make identifying entries easier, but `name` could serve the same purpose without adding additional complexity to every record in json files.

**Comment by ajurasz** [comment]
@tdziurko can we make this task obsolete? I will use this `id` in blog url (https://github.com/jvm-bloggers/jvm-bloggers/pull/409#discussion_r127604448)

**Comment by Niubi90** [comment]
So i shouldn't work on that task?

**Comment by ajurasz** [comment]
@Niubi90 sorry for all the confusion. In the end, I will not need this field. Please continue with your work.

**Comment by tdziurko** [comment]
@Niubi90 What is the status of this task? As we had some fruitful discussion how to approach this removal process.

**Comment by Niubi90** [comment]
Beginning. If for @ajurasz using jsonId is easier and it will make application less complex he can do it, and I will abandon taks. Yestarday I was analyzing the code , and I dont apply any huge changes to this task yet.
