### ISSUE TITLE
Subpage with team of contributors

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#288]
We could use a sub-page with list of all people who contributed to the project (3 repositories under https://github.com/jvm-bloggers).

Minimal Viable Product is to have a static list of people (name, link to GH account, photo), but if someone wants to play with GitHub API a bit, we could make this list generated dynamically (once a day for example) with statistics about contribution gathered from the GitHub (number of lines added/removed or using other factor that looks reasonable).

**Comment by kaczors** [comment]
I will do it.

**Comment by airborn** [comment]
@kaczors are You still working on that?
