### ISSUE TITLE
Open blog posts in new tabs

### ISSUE THREAD

**Issue by MateuszRasinski** [jvm-bloggers/jvm-bloggers#290]
As a user I would like to open every blog post in a new tab by clicking on the post's link. Or maybe I would like to have an additional icon to do that, to be backwards compatible.

**Comment by tdziurko** [comment]
I am not sure about this feature request. Generally anyone could open a link in a new tab by using middle button on mouse so I see a little value in forcing all users to spawn multiple tabs for each newsletter issue.

@MateuszRasinski Could you elaborate more about retionale behind this? :)

**Comment by goostleek** [comment]
I can agree that modern browsers have this feature OOTB allowing users to open links in a new tabs easily.
However, I'm not biased to any approach in that matter. I think it's been already told enough in this topic and it's worth to get to know with [all the arguments](http://ux.stackexchange.com/questions/31579/when-if-ever-should-links-be-opened-in-a-new-window) (before staring the discussion which approach is better and why;)).

**Comment by MateuszRasinski** [comment]
The reason was my workflow, I admit. However, I am convinced that this article is right: http://uxmovement.com/navigation/why-external-links-should-open-in-new-tabs/. The most important part, in my opinion, is this one: "Slowing Down User Flow". As JVM Bloggers is a link-sharing site, I would like to go to multiple sites (great for tabs). Not search and choose just one (great for single-thread).

**Comment by tdziurko** [comment]
Ok, consider me convinced :)
