### ISSUE TITLE
Rename misleading constraint names in DB tables

### ISSUE THREAD

**Issue by Fizol** [jvm-bloggers/jvm-bloggers#291]
Constraint names in tables point to old table names, eg.
pk_person (blog.id) UNIQUE; 
person_rss_unique (blog.rss) UNIQUE;
It's due to renaming without cleanup in the past. 
Task is to make review of DB and correct these names.

Now it's difficult to read and understand db scheme for newcomers.

**Comment by tdziurko** [comment]
I agree that it should be fixed :)

**Comment by Fizol** [comment]
Please assign me, I haven't such option yet (or I have)?

**Comment by Fizol** [comment]
While doing this task I spotted a problem with H2 db running in tests. I described that problem in #293. In order to accomplish this task firstly #293 is required.
