### ISSUE TITLE
Remove implicit definition of unique constraint on SETTING table due to test problems

### ISSUE THREAD

**Issue by Fizol** [jvm-bloggers/jvm-bloggers#293]
Depending on #291 
In Liquibase when you implicitly create unique constraint on column:
```xml
<changeSet id="012-create-setting-table" author="Tomasz.Dziurko">
    <createTable tableName="setting">
   (...)
        <column name="name" type="varchar(100)">
            <constraints nullable="false" unique="true"/>
        </column>
   (...)
    </createTable>
</changeSet>
```
You get 
```sql
"setting_name_key" UNIQUE CONSTRAINT, btree (name)
```
But against H2
```sql
select constraint_name from information_schema.constraints where table_name='METADATA' and column_list='NAME';
=> CONSTRAINT_A
```
This gives suprising effects (exception) when you run test with spring boot context and H2 and previously renamed constraint on tables.

Task is to remove this implicit definition and do explicit definition modyfing old changest ("012-create-setting-table"), and in the future define unique constraint names only using 'addUniqueConstraint'.

**Comment by tdziurko** [comment]
Ok, this sounds reasonable and if you want you can fix it so application (or database) behaves more predictably. But I see one major problem: you can not modify already applied changesets, you need to write   a new changeset that fixes these problems.

Also (as an extra) I would:
 * add info about this convention in naming constraints to our guidelines
 * consider adding a check that fails a build when someone do not obey this rule. This might be tricky to accomplish though :)

**Comment by tdziurko** [comment]
@Fizol What is the status of this issue? I am not sure if it is 100% complete or not :)

**Comment by Fizol** [comment]
@tdziurko Please let me check that.
As I remember I was waiting for #295 to be merged, and after waiting almost 2 months I lost my all hopes. Than you merged that, but hopes were gone :)
