### ISSUE TITLE
Missing newly added blog in new blogs section

### ISSUE THREAD

**Issue by prondzyn** [jvm-bloggers/jvm-bloggers#296]
I added Paweł Chudzik's blog [this week](https://github.com/jvm-bloggers/jvm-bloggers/commit/583ce3c039a739b466f36c54123719555e87f30a) and it should be listed in [65th edition](http://jvm-bloggers.com/issue/65) but it isn't. 

Please find the reason.

**Comment by tdziurko** [comment]
Issue no longer occurs after new release

**Comment by prondzyn** [comment]
Great! Thanks!
