### ISSUE TITLE
Setup production monitoring for main website and rss

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#297]

**Comment by goostleek** [comment]
We can use [restart policy](https://docs.docker.com/engine/reference/run/#/restart-policies---restart) for the Docker container to force the container to start in case the server or docker daemon was restarted.

For health monitoring we can use [built-in healthcheck feature](https://docs.docker.com/engine/reference/builder/#/healthcheck) or, to be able to restart unhealthy container, [docker-autoheal](https://github.com/mcasimir/docker-autoheal).

**Comment by tdziurko** [comment]
Done using https://uptimerobot.com/
