### ISSUE TITLE
Concurrency issues in BloggersDataUpdater

### ISSUE THREAD

**Issue by airborn** [jvm-bloggers/jvm-bloggers#304]
Current version of [`BloggersDataUpdater`](https://github.com/jvm-bloggers/jvm-bloggers/blob/f3e06bb63983de82cf89193964d6c37c9b38bf8a/src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java) contains an inner class [`UpdateSummary`](https://github.com/jvm-bloggers/jvm-bloggers/blob/f3e06bb63983de82cf89193964d6c37c9b38bf8a/src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java#L121) holding basic statistics about updated entries.

As the entries are processed in [parallel](https://github.com/jvm-bloggers/jvm-bloggers/blob/f3e06bb63983de82cf89193964d6c37c9b38bf8a/src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java#L37) there is a probability of race condition in `UpdateSummary`.

Additionally in the [`updateData`](https://github.com/jvm-bloggers/jvm-bloggers/blob/f3e06bb63983de82cf89193964d6c37c9b38bf8a/src/main/java/com/jvm_bloggers/core/data_fetching/blogs/BloggersDataUpdater.java#L32) method the `Bloggers` collection is traversed twice which should be unnecessary.

**Comment by adamdec** [comment]
I have not seen the exception but looking quickly at the code I can say that introducting Atomics in UpdateSummary will do a work here. Also we can put final on the argument passed in the constructor. You are right...collection can be traversed once.

**Comment by airborn** [comment]
You won't see any exception, what can happen is incorrectly summed number of updates/creations. That is not something that would easily noticeable you would have to count log statements and compare them with the ones from `UpdateSummary`.

Yes, switching to `AtomicInteger` was my first approach, but in the end I've implemented this slightly different. Instead of modifying `UpdateSummary`, I'm returning a status from each method call. That way we don't need to modify anything passed to the methods.
