### ISSUE TITLE
There's no space between last item on the archive page and footer

### ISSUE THREAD

**Issue by pwittchen** [jvm-bloggers/jvm-bloggers#309]
There's no space between the last item on the archive page and footer. There should be margin about 10px. Please, see screenshot below.

![screenshot](https://cloud.githubusercontent.com/assets/695319/22573644/40238a40-e9aa-11e6-954c-fe87ffec4a72.png)

The environments on which problem can be reproduced:
- environment 1
  - Ubuntu Linux 16.04 LTS
  - Google Chrome 53.0.2785.116 (64-bit)
- environment 2
  - macOS Sierra
  - Google Chrome 55.0.2883.95 (64-bit)

It's worth mentioning that on the other web pages problem does not occur.

**Comment by Niubi90** [comment]
I will work on that :)
