### ISSUE TITLE
Add links to the previous and next issue on the issue page

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#319]
When reading a newsletter issue, there should be a link to the next/previous issue if they exist.

**Comment by tdziurko** [comment]
Any update on this @Niubi90 ? :)

**Comment by Niubi90** [comment]
Through this week feature should be implemented

**Comment by Niubi90** [comment]
I haven't enough time to do it, yet. If this task need to be fast feel free to take it.

**Comment by tdziurko** [comment]
Ok, returning issue to the pool :)

**Comment by ajurasz** [comment]
@tdziurko any suggestion where to put these links?

Here are some proposals from my side:

1.
![image](https://cloud.githubusercontent.com/assets/3949308/25752723/64ccbe32-31b9-11e7-9bf6-f0a2023ac2e4.png)

2.
![image](https://cloud.githubusercontent.com/assets/3949308/25752778/9bfe1dba-31b9-11e7-9823-60384d5aff79.png)

3.
![image](https://cloud.githubusercontent.com/assets/3949308/25752979/3d3bae18-31ba-11e7-9ad5-5189158cf3a3.png)

I am open to suggestions.

**Comment by tdziurko** [comment]
I thought about putting them below actual newsletter panel only, not sure if they should be added at the top too... :)

**Comment by ajurasz** [comment]
Well, my personal choice would be 3 but all of them felt strange when present at the top. In the bottom, it will be more natural not sure why I didn't think about it in the first place. 

Please, could you assign this task to me or put 'In progress' label? I just need to setup project and will start working on this with pleasure.

**Comment by airborn** [comment]
3. looks really nice. Maybe we should put it both at the top and on the bottom?

Sorry, cannot assign it to You until @tdziurko adds you to the project

**Comment by tdziurko** [comment]
@ajurasz please accent invitation to the team so I could assign you.
