### ISSUE TITLE
Cleanup javascript libs

### ISSUE THREAD

**Issue by airborn** [jvm-bloggers/jvm-bloggers#336]
Currently project looks more like a javascript project then java one.
![stats](https://monosnap.com/file/iqy9QnawNlKU1d1HNE6zz0xWvuXA3Y.png)

We have a lot of unused javascript dependencies that can be safely removed. Also there are some duplication between user/admin theme, and we need an investigation whether those can be safely removed.

**Comment by tdziurko** [comment]
Can I mark this as resolved?

**Comment by airborn** [comment]
We now have

>  CSS 48.0%	 JavaScript 18.7%	 Java 18.4%	 Groovy 11.1%	 HTML 3.7%	 Shell 0.1%

Still far from good, but I think that we need to live with with it for now.
