### ISSUE TITLE
Add a way to filter out 'daj się poznać' related posts in RSS

### ISSUE THREAD

**Issue by devopsd** [jvm-bloggers/jvm-bloggers#341]
Add a way to filter out posts related to "Daj się poznać" competition in RSS to reduce noise to signal ratio.

**Comment by tdziurko** [comment]
Any ideas/suggestions how it could be accomplished?

**Comment by goostleek** [comment]
At the moment the only way to exclude the content from RSS feed is to exclude it by author only which was introduced in #214. I don't see any reasonable way to distinguish posts related to "Daj się poznać" initiative but I'm opened for ideas.

**Comment by tdziurko** [comment]
One idea that came to my mind is that we could mark those bloggers producing content for DSP as "requiring moderation" so I could manually accept only reasonable posts :)

**Comment by Koziolek** [comment]
@tdziurko, but when you introduce manual moderation then you need to take care about other tags/categories/actions. In RSS we have `item/category` tag that could be useful in this case. Similar situation in atom, we have [`atom:category`](https://tools.ietf.org/html/rfc4287#section-4.2.2) element.

**Comment by tdziurko** [comment]
Should be solved by #412
