### ISSUE TITLE
Bump dependencies to latest ones (May 2017)

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#362]
Bump dependencies:
 * spring-boot to 1.5.3
 * wicket to 7.7.0
 * wicket-spring-boot to 1.0.8
 * replace javaslang with vavr

**Comment by goostleek** [comment]
What about other [outdated dependencies reported by Versioneye](https://www.versioneye.com/user/projects/5798bd4874848d004b927ac7#tab-dependencies)?

**Comment by tdziurko** [comment]
Wicket bumped to 7.6.0 as one sub-projects is not yet available for 7.7.0 (planned release next week)
Javaslang bumped to latest version before renaming to Vavr, we need to wait with migration to Vavr until spring-data updates its converter to vavr :)
