### ISSUE TITLE
Add RSS page with rss usage description

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#375]
We need a subpage (accessible from top navigation bar) with details about RSS (link, how it could be filtered, etc.)

**Comment by kraluk** [comment]
As I'm trying recently to broke something with the RSS, I'll also create the proposed page with some information about the given feed :)

**Comment by tdziurko** [comment]
Ok @kraluk , I will assign you to this issue once you accept invitation.

**Comment by kraluk** [comment]
@tdziurko, thanks for the invitation - I've already assigned myself to this issue - I hope that I'll be not punished for that :)
