### ISSUE TITLE
Links to top X don't work in 1.9.0

### ISSUE THREAD

**Issue by szpak** [jvm-bloggers/jvm-bloggers#380]
http://jvm-bloggers.com/top-articles/2017/05 returns 302 and redirects to http://jvm-bloggers.com/top-articles/ . Tested with the production instance.

**Comment by tdziurko** [comment]
Nothing suspicious in the logs, after restart it started working. Will keep it open for some time, meanwhile I will add more logging there.

**Comment by tdziurko** [comment]
I have also added a monitoring via UptimeRobot to check if one of top articles summary pages renders properly

**Comment by tdziurko** [comment]
Problem didn't occur for over a month, I am closing the issue.
