### ISSUE TITLE
Allow to post to FacebookPage from admin panel

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#390]
Sometimes as an Admin I would like to post something manually to wall of JVM Bloggers page. So accomplish this I need a form with text area (for message) and text field (for link) so `FacebookPost` object could be stored in the database and then picked up to posting by existing `FacebookPublishingScheduler`.

**Comment by airborn** [comment]
My question would be should this be posted only on a facebook, or should we publish this on jvm-bloggers.com as well. I'd like to see it on a site as well and have it published in our newsletter RSS, and on twitter as a link to our site.

**Comment by thepowerofra2000** [comment]
I think I can work on this, should it be only-facebook variant?

**Comment by tdziurko** [comment]
Let's start with FB only.
