### ISSUE TITLE
Add RSS feed with newsletter issues

### ISSUE THREAD

**Issue by airborn** [jvm-bloggers/jvm-bloggers#401]
Add a separate RSS feed with newsletter issues. 
Consider changing feeds URIs to clearly indicate feed content (add redirection from old feed).
Add RSS icons for each feed that should be visible on every subpage of the project.

**Comment by tdziurko** [comment]
`Consider changing feeds URIs to clearly indicate feed content (add redirection from old feed).`
Could you elaborate?

**Comment by airborn** [comment]
Currently single blog entries are available under `/pl/rss` it may be a good idea to move it to something like: `/feed/blogpost`, `/feed/posts` or some thing similar.
Feed for issues can be placed under `/feed/newsletter` or `/feed/entries`
Last part is about redirection from `/pl/rss` to `/feed/blogpost`

**Comment by kraluk** [comment]
Working on it.

**Comment by tdziurko** [comment]
Free to take due to inactivity

**Comment by kraluk** [comment]
Well, I'm back and I'll try to implement this feature one more time - and I hope that this time my work will be successful :)
