### ISSUE TITLE
Allow readers to suggest varia entries

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#435]
Sometimes people know about something interesting that should land in a `Varia` section. Currently, they have to find a contact email address and send a message. It would be simpler to have a form with 2-3 fields on jvm-bloggers.com page so they could fill it.

Basic requirements: 
1. On the right panel link with heading "Masz coś wartego uwagi?" and a link below "Daj nam znać" which redirects to a separate page.
2. On this page we need following fields:
 - link field
 - Text area "Dlaczego ten link powinien znaleźć się w sekcji Varia?"
 - optional text field: Podpisz się jeśli chcesz.
3. After user submits this form, we should create a new entry in a table `VARIA_SUGGESTIONS`.

**Comment by ajurasz** [comment]
Looks like an interesting feature. I will start working on this and #436 as well.
