### ISSUE TITLE
Cannot insert new Blog into database during first run

### ISSUE THREAD

**Issue by solveretur** [jvm-bloggers/jvm-bloggers#440]
When someone tries to run the app locally it works, however no data is inserted into BLOG table due to moderation_required nullable constraint violation

![image](https://user-images.githubusercontent.com/20731076/30118783-33eb1f4e-9324-11e7-8b45-f93e7b1b3bd5.png)

Therefore after login at localhost:8080/admin-blogs  there are no blogs to moderate 

![image](https://user-images.githubusercontent.com/20731076/30118821-4aeb5c90-9324-11e7-8977-8e80752bc144.png)

**Comment by tdziurko** [comment]
Fixed by #441
