### ISSUE TITLE
Add sorting to blog list in the admin panel

### ISSUE THREAD

**Issue by airborn** [jvm-bloggers/jvm-bloggers#442]
It would be nice to add sorting possibility to the `admin-blogs` table. 

I'm currently considering adding one more column to this table, so it would be nice if this solution would also support sorting by numeric values.

**Comment by gsancewicz** [comment]
Hi. I would like to work on this issue. It is my first time when i work with wicket and i have one question first. Why tables in this project are written with DataView (and CustomPagingNavigator) instead of using DefaultDataTable?

**Comment by tdziurko** [comment]
At the moment of writing, we didn't need so sophisticated component so a simpler one was chosen. But if we want to add sorting on columns, DataTable is the way to go I think.
