### ISSUE TITLE
Incorrect message on Twitter with new issue announcement

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#457]
Source: https://twitter.com/JVM_bloggers/status/936550555878641665

    Nowy numer #115 już online - http://jvm-bloggers.com/issue/115  z postami m.in. , @softwaremill i @CodeCouple_pl #java #jvm

Problem lies in `m.in <here should be some twitter handle>, @softwaremill (...)`. It looks like there should be a twitter handle there but it wasn't present (maybe random picked an author without twitter handle specified?).

**Comment by dmydlarz** [comment]
Hey, I want to fix it 🤘
