### ISSUE TITLE
Increase Twitter message length

### ISSUE THREAD

**Issue by darek1024** [jvm-bloggers/jvm-bloggers#462]
We can go with 280 instead of 140

**Comment by dmydlarz** [comment]
@tdziurko ?

**Comment by rumid** [comment]
I've spotted max length was increased to 250 chars: https://github.com/jvm-bloggers/jvm-bloggers/blob/master/src/main/java/com/jvm_bloggers/core/social/twitter/TweetContentGenerator.java#L25 
is it intended?

**Comment by rumid** [comment]
@tdziurko I think it might be closed since: https://github.com/jvm-bloggers/jvm-bloggers/commit/4af38d0ff42c6bafd01368c2abd6d8ad16dc813f
