### ISSUE TITLE
Refactor Twitter messages generator

### ISSUE THREAD

**Issue by darek1024** [jvm-bloggers/jvm-bloggers#463]
Right now there are two copies for message to handle two & three Twitter handles.
It could be refactored, so there is one copy template that is able to handle `N` Twitter handles.

Class: https://github.com/jvm-bloggers/jvm-bloggers/blob/master/src/main/java/com/jvm_bloggers/core/social/twitter/TweetContentGenerator.java

**Comment by rumid** [comment]
With twitter message to be max 280 chars, constant part of message takes 94 chars(23 constant size of links included), so we have free 184 chars which can be used for 3 twitter names. According to: https://help.twitter.com/en/managing-your-account/twitter-username-rules name max length is 15 chars + '@' char.
Knowing that we cannot extend 280 chars (94 + 3*16 = 142).
I can take this issue and remove short message template.
