### ISSUE TITLE
Update Lombok version and remove old-style constructor autowiring

### ISSUE THREAD

**Issue by chlebik** [jvm-bloggers/jvm-bloggers#520]
In many places application uses old Java-7 style Lombok ability to generate all-args constructors annotated with **@Autowired** dependency, eg:

`@AllArgsConstructor(onConstructor = @__(@Autowired))`

IMHO it should be at least changed to suggested in Lombok documentation form:

`@AllArgsConstructor(onConstructor_ = {@Autowired})`

and if it is possible to actually remove it completly - since Spring **4.3.0** when there is only one constructor per spring-managed bean autowiring occurs automatically. Of course there are also situations where @NoArgsConstructor is used on the bean and then this functionality won't work. However it should be tried and tested.

**Comment by tdziurko** [comment]
Fixed by #540
