### ISSUE TITLE
Prevent showing same posts in two newsletters

### ISSUE THREAD

**Issue by ggodlewski** [jvm-bloggers/jvm-bloggers#535]
Lots of entries in:
http://jvm-bloggers.com/issue/189
http://jvm-bloggers.com/issue/190
are the same, especially in company section.

Some of those entries are older then week:
"5 reasons why you should learn Java by Applantic" March 2018

It's supposed to be "cotygodniowy newsletter z najnowszymi wpisami". Please fix it.

**Comment by tdziurko** [comment]
Fixed
