### ISSUE TITLE
blog posts not showing up neither in rss nor in weekly summary

### ISSUE THREAD

**Issue by pchudzik** [jvm-bloggers/jvm-bloggers#545]
Blog posts from [blog.pchudzik.com](https://github.com/jvm-bloggers/jvm-bloggers/blob/master/src/main/resources/blogs/bloggers.json#L862) are not showing up in rss nor in weekly posts summary.

**Comment by tdziurko** [comment]
Still not solved. Something is not working in the production but when I've run the application on localhost connected to Production DB, it parsed your RSS file correctly and added posts. 

So this is something more subtle appearing only on prod. Maybe it is something with docker-compose network stuff or I don't know... will investigate :)

**Comment by pchudzik** [comment]
I've noticed that after migrating my hosting to netlify my posts are picked up correctly. I guess it was something with hosting settings...

I had the same problem with them when trying to add a deployment pipeline from TravisCI. They've been simply blocking some traffic from TravisCI IPs, or maybe AWS who knows...

I'm going to close this issue. Feel free to reopen if needed.
