### ISSUE TITLE
Subpage with invitation link to JVM Poland Slack

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#580]
We need a subpage (accessible from top menu) with an active invitation link to the JVM Poland Slack.

1. Page should have some test (let's start with Lorep ipsum)
2. Page should have a invitation link to JVM Poland Slack
3. Page shjould be bookmarkagle via `<root>/jvm-poland-slack`
4. We should have a link (with red font) to this page in the top menu (between `RSS` and `O projekcie`)
5. Link should be configurable via `application.properties` file

**Comment by mtszpater** [comment]
I could do it.
