### ISSUE TITLE
Store tags/categories for each blog post/video/

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#593]

**Comment by mtszpater** [comment]
Hi @tdziurko, can you describe how that tags should works?

**Comment by tdziurko** [comment]
@mtszpater Most of the RSS entries contain some type of tags/categories, like in mine http://tomaszdziurko.com/feed/ there are 

 		<category><![CDATA[Reading]]></category>
		<category><![CDATA[books]]></category>
		<category><![CDATA[learning]]></category>
		<category><![CDATA[reviews]]></category>

Other blogs could have different format (not in CDATA, etc.). So the idea is to:
1. Store them in a separate table with as records (id, tag, blog_post_id)
2. Store them for all new blog posts
3. Create logic that will fetch this data from existing blogs posts and create such records for them.

Probably we need to sanitize/normalize this data before storing it in the DB (toLowerCase, remove CDATA, etc.).

**Comment by asciborek** [comment]
@mtszpater are you going to implement this functionality? Otherwise I would like to resolve this issue

**Comment by mtszpater** [comment]
@asciborek you can go ahead and take it.

**Comment by asciborek** [comment]
@tdziurko 
Please assignee it to me ;)

**Comment by tdziurko** [comment]
Done in #622
