### ISSUE TITLE
Lowercase posts with more than 20% of chars in uppercase

### ISSUE THREAD

**Issue by jakubnabrdalik** [jvm-bloggers/jvm-bloggers#609]
A lot of authors on the net apparently abuse JVM Bloggers by posting all caps
For example
```
- ANGULAR CLI DLA PROGRAMISTÓW JAVA - ANGULAR W 45 MIN by Programuj z Bykiem
```
I suggest normalizing the data by forcing lower case on all posts/titles that have more than 20% of chars in uppercase.
Also, removing all emojis would be nice.

**Comment by puradawid** [comment]
:+1: Yeah this may be a bit annoying.

**Comment by borkok** [comment]
I would like to give it a try, it looks like a good first issue.
