### ISSUE TITLE
Show list of recent blog posts in admin panel

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#64]
At Dashboard Page we could have a list of recent events (currently only new blog posts but with some other type of events in the future in mind)

Proposed location: http://screencast.com/t/7j6QAbHYCd

**Comment by jborkowski** [comment]
I would like to take care about this, but I need more information about types of recent events ;)

**Comment by tdziurko** [comment]
I am seeing this as a list of following events stored in one collection (table) and displayed in the location metioned above:
 - new blog post fetched
 - new blog added
 - mail sent

**Comment by tdziurko** [comment]
This could be done by events mechanism from Spring 4.2  - https://solidsoft.wordpress.com/2015/09/29/annotation-driven-event-listeners-in-spring-4-2/
or by Google Guava EventBus (but this is synchronous so kind of sucks). Or even with any other event bus tool/library that is lightweight and easy to use within the scope of one application.

**Comment by jborkowski** [comment]
I have some questions about this task. 
1) I guess that the notification list should be dynamic (if yes, how much last events should be contain)?
2) If I don't catch any event, what should be display?
3) Elements of the same type could be duplicated on the NotificationList?
4) How can I catch event from "new blog post fetched"?

**Comment by tdziurko** [comment]
1. Not sure if I understand you correctly. Events should be persisted in a separate table and UI component should display last X events on the Dashboard.
2. Component with no rows/items.
3. You will have class `ApplicationEvent` or similar with fields: id, message, eventType (as enum), date and database table with objects of this class could contain e.g. these records:
 * (1, "http://blog1/some-post", "NEW_BLOG_POST", "2016-01-01 10:12")
 *  (2, "http://blog1/rss", "NEW_BLOG", "2016-01-03 11:12")
 *  (3, "someone@example.com", "MAIL_SENT", "2016-01-02 20:00")

So I do not see how they could be duplicated.
4. Check where we call `BlogPostRepository.save` and it should be somewhere near this one.

**Comment by jborkowski** [comment]
Ok, thanks for your advice.

**Comment by jborkowski** [comment]
Hi, I would to ask if this task is still needed? I did a draft of this issue some time ago, but did not have time to publish it.

**Comment by tdziurko** [comment]
We can have a look :)
