### ISSUE TITLE
Full text search by titles and tags 

### ISSUE THREAD

**Issue by asciborek** [jvm-bloggers/jvm-bloggers#656]
I'd like to implement searching posts by tags.  I suggest to use an autocomplete search bar.

**Comment by tdziurko** [comment]
Sounds good :) Could you describe the planned approach before starting implementation? Just more or less, so we know that we are on the same page? :)

**Comment by asciborek** [comment]
Of course, I will describe my planned approach as soon as I will have one ;)

**Comment by asciborek** [comment]
@tdziurko 
I think the best approach is to use Hibernate-Search and Lucene. Titles of blog posts can be indexed as well, so a user would be able to search by title or tags. I'd like to create a new page containing search filters  :)

**Comment by tdziurko** [comment]
Sounds good :) additional ideas/comments:
1. Separate page - awesome, it would be cool to make it bookmarkable, something like jvm-bloggers.com/search?phrase=micronaut or something similar
2. Design it in a way that adding a description and content to the index engine later on would be easy.
