### ISSUE TITLE
Incorrect link with whitespaces (issue #295)

### ISSUE THREAD

**Issue by RG9** [jvm-bloggers/jvm-bloggers#690]
Hi, issue [#295](https://jvm-bloggers.com/issue/295) has this entry:
```
 - podcast Inside Java o możliwościach pattern matchingu w JDK 17 - link
 ```
generated link contains whitespaces, which results in HTTP 404:
https://jvm-bloggers.com/%E2%80%9CPattern%20Matching%E2%80%9D%20with%20Gavin%20Bierman

**Comment by tdziurko** [comment]
Fixed on production, correct link is https://www.youtube.com/watch?v=pnXlCvYspYk
