### ISSUE TITLE
Replace cz.alenkacz.gradle.jsonvalidator with another way to validate json correctnes

### ISSUE THREAD

**Issue by tdziurko** [jvm-bloggers/jvm-bloggers#717]
Gradle plugin `cz.alenkacz.gradle.jsonvalidator` is no longer mainanted and stopped working with latest Gradle version. We need another way to validate that json files with blogs, podcasts, etc are valid.

**Comment by kraluk** [comment]
Will try to handle this issue. I'm on it.

**Comment by tdziurko** [comment]
@kraluk Awesome! :) Please pull master as I've just migrated to JDK 17. Everything should work just fine. If not, please let me know :)
