### ISSUE TITLE
New personal blogs don't appear at jvm-bloggers

### ISSUE THREAD

**Issue by zyxist** [jvm-bloggers/jvm-bloggers#726]
Hello, I noticed that despite being merged 8 days ago, my blog still hasn't showed up at jvm-bloggers.com. Here's the PR: https://github.com/jvm-bloggers/jvm-bloggers/pull/722

At the same time, I see that the change from another PR merged at the same time https://github.com/jvm-bloggers/jvm-bloggers/pull/723 got included in the newest summary #339. 

@tdziurko could you take look at the issue? Is the feed valid?

**Comment by zyxist** [comment]
@tdziurko - have you looked why my blog did not appear on jvm-bloggers.com despite adding it to the JSON file? It's been 2,5 months since I raised the PR, and it's still not there... :/

**Comment by tdziurko** [comment]
Your blog will appear in the next newsletter. I think I've fixed the problem :) Please do not hesitate to reopen if this problem occurs again.
